### ISSUE TITLE
Encoding or Decoding fails when Longitude is -ve

### ISSUE THREAD

**Issue by idbates** [itinero/OpenLR#76]
The following is a modified version of Samples.OSM Program.cs - it uses a OSM pbf file of the Derbyshire in the UK. When the binary OpenLR is decoded the decode codec returns Longitude location -178. Code decode worked for sample in Cambridgeshire UK with a positive Longitude. Link to OSM data used to create issue [https://1drv.ms/u/s!AkOVlf_yN86BidVJDq2vnRX5H9UEUg](https://1drv.ms/u/s!AkOVlf_yN86BidVJDq2vnRX5H9UEUg)

            // build routerdb from raw OSM data.
            // check this for more info on RouterDb's: https://github.com/itinero/routing/wiki/RouterDb
            var routerDb = new RouterDb();
            using (var sourceStream = File.OpenRead(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "derbyshire.osm.pbf")))
            {
                routerDb.LoadOsmData(sourceStream, Vehicle.Car);
            }

            // create coder.
            var coder = new Coder(routerDb, new OsmCoderProfile());

            // build a line location from a shortest path.
            // REMARK: this functionality is NOT part of the OpenLR-spec, just a convenient way to build a line location.

            var line = coder.BuildLine(new Itinero.LocalGeo.Coordinate(52.932129f, -1.521154f),
                new Itinero.LocalGeo.Coordinate(52.929387f, -1.505844f));
            var lineGeoJson = line.ToFeatures(coder.Router.Db).ToGeoJson();

            // encode this location.
            var encoded = coder.Encode(line);
            Console.WriteLine(encoded);

            // decode this location.
            var decodedLine = coder.Decode(encoded) as ReferencedLine;
            var decodedLineGeoJson = decodedLine.ToFeatures(coder.Router.Db).ToGeoJson();

            Console.ReadLine();

![image](https://cloud.githubusercontent.com/assets/7227960/23726337/dd243d56-044b-11e7-9a9c-ebf5028b992d.png)

![image](https://cloud.githubusercontent.com/assets/7227960/23726176/3e7f7d3c-044b-11e7-997b-46c6903f0c77.png)

**Comment by xivk** [comment]
Ouwch, thanks for reporting...

**Comment by idbates** [comment]
Hi Ben,

Thanks for acknowledging the issue.
Any idea when you might get around to fixing this? We were looking at using Itinero/OpenLR to decode OpenLR from a TomTom traffic feed. There aren’t really many alternatives around in .NET unless we either write our own or port TomTom OpenLR.org code from Java.

Thanks,
Ian Bates, MEng MIET MCTS
Principal Software Developer,  Transportation
D +44 (0)191 224 6523
ian.bates@aecom.com<mailto:ian.bates@aecom.com>
AECOM
First Floor, One Trinity Gardens
Quayside, Newcastle upon Tyne, NE1 2HF
T +44 (0)191 224 6500 F +44 (0)191 224 6599
www.aecom.com<http://www.aecom.com/>

AECOM and URS have joined together as one company. Learn more<http://www.aecom.com/>

**Comment by xivk** [comment]
Verified and tests, this decodes now fine to:

http://geojson.io/#id=gist:anonymous/c66ff1deb844ec84d8a39de3da89c5cb&map=16/52.9307/-1.5135

**Comment by idbates** [comment]
Thanks!

Ian Bates, MEng MIET MCTS
Principal Software Developer,  Transportation
D +44 (0)191 224 6523
ian.bates@aecom.com<mailto:ian.bates@aecom.com>
AECOM
First Floor, One Trinity Gardens
Quayside, Newcastle upon Tyne, NE1 2HF
T +44 (0)191 224 6500 F +44 (0)191 224 6599
www.aecom.com<http://www.aecom.com/>

AECOM and URS have joined together as one company. Learn more<http://www.aecom.com/>
