### ISSUE TITLE
Does Itinero/OpenLR only work with the Itinero v0.35.2-rc2?

### ISSUE THREAD

**Issue by idbates** [itinero/OpenLR#77]
Does it only work with v0.35.2-rc2 or can I upgrade Itinero and other dependencies?
Thanks!

**Comment by xivk** [comment]
You should be able to update. I didn't have the time yet to update the dependencies here sorry.

With the release of Itinero 1.0 we will be working to release a stable of this library too. But, yes, you should be able to upgrade. If you have issue feel free to post them here, I'll try and help to fix them.

**Comment by idbates** [comment]
Thanks that’s great.

Ian Bates, MEng MIET MCTS
Principal Software Developer,  Transportation
D +44 (0)191 224 6523
ian.bates@aecom.com<mailto:ian.bates@aecom.com>
AECOM
First Floor, One Trinity Gardens
Quayside, Newcastle upon Tyne, NE1 2HF
T +44 (0)191 224 6500 F +44 (0)191 224 6599
www.aecom.com<http://www.aecom.com/>

AECOM and URS have joined together as one company. Learn more<http://www.aecom.com/>

**Comment by idbates** [comment]
I just submitted an issue #79  with the decoder  - I realise it could be due to this very problem - if this is the case happy to update project. Not had time as yet! Thanks

**Comment by xivk** [comment]
Closing this issue, upgraded to 1.0 now, working towards a release soon.

There is issue #79 still.
