### ISSUE TITLE
OpenLR code decoder ignoring endpoint bearing / not taking shortest route

### ISSUE THREAD

**Issue by idbates** [itinero/OpenLR#79]
The OpenLR code C/7+1SWwURt5JfZ8A2ccDw== decodes to the following route using Itinero/OpenLR ( version 0.4.4.0 and Itinero version 0.35.2.0)

![image](https://cloud.githubusercontent.com/assets/7227960/24507166/aa87f46a-1557-11e7-9f45-fa05bba13ca3.png)

This OpenLR code originated from a TomTom traffic feed and TomTom's decoder gives the following routing. According to TomTom support the decoder may not be taking the endpoint bearing into account.

![image](https://cloud.githubusercontent.com/assets/7227960/24507468/71a5301c-1558-11e7-959d-dfbb1fba0779.png)

The OSM file used for the matching can be downloaded from https://1drv.ms/u/s!AkOVlf_yN86BidpmtpDTt-iGd_IxUA

**Comment by xivk** [comment]
Related to this issue:

Case 1
Name: 21122012 1216-N378.json

6.77369213104248 52.9741401672363, 
6.83290004730225 52.9855003356934, 
6.93771266937256 53.0042343139648

Encode: http://geojson.io/#id=gist:hcoppen/d0d4b977a439f1861bbf63acdda88fe9&map=13/52.9883/6.8527

OpenLR CwTQkyWrri+oyD/9CvcacQQA

Decode: http://geojson.io/#id=gist:hcoppen/56ace88bfc1e2c4fb77709efa74ea7e6&map=13/52.9883/6.8527


Case 2
Name 22112011 91332-N342.json

6.82557249069214 52.2756652832031, 
6.9128098487854 52.3101997375488, 
6.93901014328003 52.3209991455078, 
6.99834203720093 52.3690414428711

Encode: http://geojson.io/#id=gist:hcoppen/2bcdfbbea71a4d0e802f3d70f49b10f7&map=13/52.3223/6.9118

OpenLR: CwTajyUsfy+ntS8qFAITZGQUMhBdE3QAAA==

Decode: http://geojson.io/#id=gist:hcoppen/dbb8025471dc0b7c1147d8218e91270d&map=13/52.3223/6.9118

**Comment by xivk** [comment]
Also related to this location:

http://geojson.io/#id=gist:anonymous/43e533f891cfe5f987e1442770ab3b1f&map=19/51.54719/4.18277
http://geojson.io/#id=gist:anonymous/424aeeb2aa76a408eb28c640abe93819&map=19/51.54713/4.18281

**Comment by xivk** [comment]
@idbates Does this OpenLR string come from some other system? Or is it also generated by this library?

**Comment by idbates** [comment]
Other system - The OpenLR code is from TomTom’s traffic flow feed.
It describes a series of links on their network – they sent a description of the expected results when decoding.
Ian Bates, MEng MIET MCTS
Principal Software Developer,  Transportation
D +44 (0)191 224 6523
ian.bates@aecom.com<mailto:ian.bates@aecom.com>
AECOM
First Floor, One Trinity Gardens
Quayside, Newcastle upon Tyne, NE1 2HF
T +44 (0)191 224 6500 F +44 (0)191 224 6599
www.aecom.com<http://www.aecom.com/>

AECOM and URS have joined together as one company. Learn more<http://www.aecom.com/>

**Comment by xivk** [comment]
Ah ok, so assuming it's 100% correct then... ;-) Thanks! I have this decoding now:

https://gist.github.com/xivk/1b7eb5e86e5c5c8bba7e803572146e30

It seems the bearing doesn't weigh heavy enough compared to classification of road comparisons. That doesn't make sense, the bearing should always be more important so I'm changing that.

There is something weird going in with this encoding. It decodes as FR3, that seems low for the road it's on, also the bearing at the end location seems incorrect. Checking this first before I commit the fix.
