### ISSUE TITLE
[question] decodedLine.Edge has negative edge numbers

### ISSUE THREAD

**Issue by skinkie** [itinero/OpenLR#87]
If I try to decode "CwReMiNSjSOYEvyqAjIjaAIG" (in the Luxembourgh scope). I end up with several negative Edges. What do these values represent?

**Comment by xivk** [comment]
If I'm correct they represent the edge by id and the direction is the sign. You can get the edge id by removing the sign and subtracting 1 (edge 0 = -1/1).

I could be wrong, it has been a while since I worked on this.

**Comment by skinkie** [comment]
@xivk I assumed something in the direction. Your hint did the trick.
```C#
if (tmp < 0) {
   tmp = Math.Abs(tmp) - 1;
}
```
